- name: Copy the export file to remote server
  copy: src=exports dest=/etc/exports owner=root group=root mode=644
  notify:
  - InstallClientPackages
  - CreateClientMount
  - ClientMountServerResources
