- name: Install all mariadb packages (Client and server)
  yum: pkg={{ item }} state=latest
  with_items:
  - "{{ dbserver_pkg }}"
  - "{{ dbclient_pkg }}"
  notify:
  - StartDBService
  - RunSecureInstallPause
  - RestartDBService
  - CopyBkupFile
  - CreateRemoteDB
  - DisplayCreationResults
  - RestoreRemoteDB
  - TestDBResults
  - ShowDBResults
- name: Add a backup CRON job to run every day at midnight
  cron: name="DBBackup" minute="0" hour="0" job="mysqldump -u root -ppassword123 --database {{ dbinstancename }} > dbbkup.sql"
