--- #master playbook for Role baed Apache web deplayment
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: How long the ROLE took to run
    raw: date > /home/test/duration.log
  roles: 
  - redhat.apachewebserver
  post_tasks:
  - name: How long the ROLE took to run
    raw: date >> /home/test/duration.log


