--- # this works only if the destination file exists
- hosts: exam
  tasks:
    - name: add hostname to config
      lineinfile:
        dest: /home/test/hostname.conf
        regexp: ^Hostname=.*
        insertafter: ^# Hostname=
        line: Hostname={{ansible_hostname}} 
